
 # Test sentences
test_sentences = [
  "Hello to all of our listeners today.",
  "for this episode of untethered to rooted, we'll be exploring how grief can show up later than we expect in a delayed way or years later.",
  "and sometimes it's an event that prompts this grief to come up or interaction or a life situation.",
  "and for our guest it was the pandemic.",
  "and specifically during the more lockdown period when she was spending more time with herself and the space during this period gave her time to process some things that hadn't been processed yet.",
  "and we know that grief can be about significant changes.",
  "this is um, about events, that happen in your life or situations that impact our lives significantly.",
  "and when these life transitions come and we've experienced significant loss in particular, there's just so many different feelings and questions that arise.",
  "and realizing that some things about us change as we allow ourselves to grieve and heal.",
  "and so our guest today will be discussing more about this.",
  "and so before we get into it, i'd love to introduce Ciera and, um, by way of introduction, i'm gonna read a little bio, and then i'm gonna actually have her share a little bit more about herself.",
  "so Ciera is a dedicated advocate for diversity, equity, and inclusion.",
  "she brings a wealth of experience and passion to her role as the chief diversity, inclusion, and belonging officer at crisis connections in seattle, where she is the community engagement lead for the nine one one call diversion project, one of the first partnership pilots in the country.",
  "additionally, she is the founder and principal consultant of the do better project llc.",
  "originally, she hails from columbus, ohio, but she now calls seattle her home.",
  "and having honed her skills and expertise during her time in pennsylvania.",
  "uh, shout out to chatham, twenty fourteen.",
  "um, Ciera's journey has taken her from the united states to a fulbright hays grant in ethiopia, exploring the intersection of community organizing and education.",
  "her diverse background encompasses roles ranging from empowering at risk youth transitioning out of foster care to crafting compelling narratives as a writer for the pittsburgh post gazette.",
  "and Ciera is now pursuing her master's in education at the harvard graduate school of education.",
  "so welcome, Ciera thank you so much, dana.",
  "it's a pleasure to be on the podcast with you.",
  "and i'm just thinking about what shall i say about myself.",
  "i'm working really hard to not orient my story around my work or, um, my achievements.",
  "albeit very important, but there's more to me, um, than than what's on the paper.",
  "and i am very eager to actually learn more about what that story means to me.",
  "um, and so for now, i i just tell people that i am working towards my north star, which is to keep people safe.",
  "and at the moment, i am doing and being all the things that keep me aligned with my north star, and that will evolve over time.",
  "yeah.",
  "working and aligning with your north star.",
  "i love that.",
  "that's, uh, that's something important to keep in mind.",
  "um, and it sounds like it's a compass for you too.",
  "so yeah.",
  "yeah.",
  "well, i've since we don't wanna just, um, only have you share about your achievements or around your work identities, i'd love for you to share just what are some identities that are important to you.",
  "who are you? yes.",
  "um, so i am a person with multiple sclerosis, um, and i i also identify as a person with a disability because i have ms.",
  "and that has been a journey in itself to come to that realization for me that it's okay to tell people that i i have ms, and, yes, it is a disability.",
  "and it is what it is.",
  "i i don't evaluate it negatively or positively.",
  "it's it doesn't have that type of charge in my life, um, and i don't want it to.",
  "um, it's just it's just me.",
  "and i am a traveler.",
  "i've traveled to over seventy seventy eight countries at this point.",
  "oh.",
  "um, i've been to every continent except for antarctica, but i am prepping my body to endure that that adventure, um, in time, and i am an explorer and adventurer.",
  "i always love trying new things.",
  "i like to rock climb, top rope, and bouldering.",
  "um, i'll be learning how to paddle board sometime this summer.",
  "i am also a lifelong learner.",
  "i'm always in a book or taking some sort of class or just trying a new skill, not only to build neuropathways, but just to expand the limits of who i thought i was.",
  "and so i am currently in a jazz vocal class, and i i have a solo at my rehearsal coming up.",
  "and, um, recently, i took a stand up class, and i still do stand up.",
  "and i took some improv classes after i realized, oh, i'm not too bad at stand up.",
  "and i, uh, am a part of a team of all black improvisers, and i think that's very rare in this region, the pacific northwest.",
  "but i think if there i'm at a point in my life where if there isn't a space, i'm not going to run and identify where another space is.",
  "i think i'm in a point where i'll just create it.",
  "i, uh, there there's a quote, um, by james baldwin that's escaping me, and i i don't wanna butcher it, um, there is a quote about the need to create spaces if you don't see it, and that that is okay.",
  "yeah.",
  "um, and i that was my intention of creating, um, this space for black improvisers in seattle, um, so that we could have the psychological safety to create and tell the stories that we wanna tell.",
  "and i i'm a i'm a lover.",
  "i'm a thinker.",
  "i'm a writer.",
  "um, i actually have a substack that is a secret.",
  "oh, okay.",
  "maybe i'll share the link, but i i write some things about life.",
  "and, yeah, i'm just expanding and being, and that's where i am in this moment.",
  "yeah.",
  "i really hear that.",
  "there's so there's so many parts of you that are so important, and i just appreciate you sharing all those parts with us here.",
  "and, um, wow, you are.",
  "like, i think the theme i think you said it so beautifully.",
  "the theme is just, like, a lot of expansion, um, a lot of expanding into many different things, especially as, like, an explorer and an adventurer.",
  "i'm wondering of some of those identities, either that you've named or maybe there are things you haven't named.",
  "um, are is there anything that people may not know about you, but it's important for what you'll share with us today? oh, of course.",
  "um, so things that people don't know about me is that i'm a deep introvert.",
  "and so in my professional life, people might say, oh, you're a good speaker.",
  "oh, you just have ease.",
  "like, you're connecting people.",
  "you know all these things.",
  "and i think, oh, i it appears that way because i use one of my strengths of just loving knowledge and and appreciating beauty.",
  "and for me, beauty is process.",
  "and for me, i i think i can lean into those strengths of mine so that people don't recognize that i'm an introvert.",
  "um, but the ways that i do show up as an introvert, um, is that i am i guard a lot of my stories and my most, like, inner depths and and emotions.",
  "mhmm.",
  "um, so when people see me, um, and i tell them, oh, yeah.",
  "i have ms.",
  "i'm gonna go, uh, get my medication.",
  "um, i'm gonna go take my injection right now.",
  "and they're like, what? i didn't know.",
  "you don't look it.",
  "and i'm like, well, i i hold on to a lot, um, which is probably why i didn't process my grief, um, the loss of my mom, um, until, like, over a decade later.",
  "yeah.",
  "and i until that's one of the most, like, personal things that people don't necessarily know, um, that you'd i'm not i'm not talking, not because i am i don't i'm avoiding or i just don't wanna be in a situation.",
  "i'm quiet because i'm observing.",
  "i'm thinking.",
  "another thing that people don't know about me is that i i'm a a first generation in a lot of sense in a lot in a lot of ways.",
  "college, moving so far from home, earning more than thirty thousand dollars a year, having extracurriculars, i am leading a life that is vastly different than a lot of folks in my my family and my community.",
  "and, again, i i don't charge it negatively or positively, um, but i do think that when anyone makes decisions that are a leap from, uh, uh, the the experiences that you you've you're accustomed to, that you've been enmeshed in.",
  "it does create another layer to your your universe or another layer to your world, and it's like you're yeah.",
  "you're part of and then you're not in some ways.",
  "and so, uh, there's also, like, other parts of my life that i don't bring into work or, like, in certain social spaces in seattle because this is the area where everybody is eating, like, single origin arugula, whatever, and they're all, like, hiking.",
  "and and i know i'm just i'm leaning into stereotypes, but it's vastly vastly different from oh, like, i go visit my family in central or northeastern ohio, and, uh, we go fishing, and it's quiet.",
  "and, um, we go to church on sunday.",
  "and it's it's a part of my world even though it is another universe from the world that that i'm in in seattle.",
  "yeah.",
  "yeah.",
  "thanks so much for sharing all those different pieces of, who you are that people may not know.",
  "and there's so many misconceptions about introverts.",
  "um, and so i'm really glad that you're here to share about just, like, how, those aren't true.",
  "as you were sharing about the introversion not sharing about your mom or or finding that people find out things about you later on, you know, i'd love for you to share maybe about your connection to this topic today about, delayed grief, grieving years later and um, even the pandemic being that space, to grieve.",
  "you started to talk about it, and i'd love for you to just share a little bit more about that.",
  "of course.",
  "so growing up, my mom was constantly sick.",
  "and i always told people that i have a mom, and i don't have a mom because she was physically present, um, but not emotionally, um, and not because she didn't want to.",
  "it's because she suffered from, honestly, medical racism.",
  "um, when she was a child, she had rheumatic fever.",
  "and at the time, i think she's she grew up poor black akron, ohio, and science has evolved, medicine has evolved, and you you treat different infections with different things based on what's going on.",
  "um, but i think they probably saw her and her family, and they're like, oh, we'll give her this.",
  "and it caused scarring in both her kidneys and her heart.",
  "and so since her, like, mid to late twenties, she would have these bouts of illness.",
  "um, by the time i was in the fourth grade, she had three or four strokes.",
  "wow.",
  "and i unfortunately witnessed the last stroke.",
  "i was in fourth grade.",
  "um, and i unfortunately had to, um, get my dad, wake him up, and and contact nine one one.",
  "and from that moment on, i i was not a child anymore.",
  "like, physically, i was a child.",
  "but i don't think that my community viewed me as a child.",
  "and i i say this because very few people ask me if i was okay or or what's going on.",
  "i just remember in school when there was a dip in my grades.",
  "and this was before, um, culturally responsive teaching and pedagogy.",
  "yeah.",
  "this was before social emotional learning.",
  "the i was a nineties baby.",
  "mhmm.",
  "and the and i was a millennial, so i was on the cusp of, like, all of these things that would come after, um, in terms of actually, i don't know, caring for the student over the test scores that they produced.",
  "and when i would go to church, people would be like, oh, we're so proud of you, but not how are you doing.",
  "even in my neighborhood, if someone saw that my hair was unkempt because my mom wasn't there.",
  "you know, there were people who reached out and many black women that i'll always be thankful to that helped.",
  "but it was more like, let's let's get you together.",
  "let's hold you, um, so that you look physically intact.",
  "but there was very few, um, moments where people asked how i was doing internally.",
  "and i do i don't have any anger towards that because i i've just processed enough to to recognize that people were doing the best that they could with what they had.",
  "and, uh, i think, culturally, and i identify as a black woman, um, and growing up in the church, i think there's no surprise to me that that was the the method.",
  "um, i think that there there is a lot of, um, in in the way that black culture manifested for me, um, there was a lot of emphasis on your whole world could be falling apart, but you better look good because it gives you a sense of dignity.",
  "and appearances.",
  "appearances.",
  "i see.",
  "yeah.",
  "yeah.",
  "um, i even remember, um, learning this early on when my great grandmother passed when i was in middle school, and i was sad, so i cried.",
  "yeah.",
  "um, and my my grandmother at the time pulled me aside, and she's like, we don't cry.",
  "youngs don't cry.",
  "and, um, she also said, you also have a run-in your stockings.",
  "so i'm gonna ask for one of your your aunts or cousins to pick you up some new pantyhose, and we gotta fix them.",
  "wow.",
  "so there was just early on just, like, messages of this is how you handle grief.",
  "this is how you handle a trying situation.",
  "you you push forward, you press on, and you look good doing it.",
  "and as i mentioned earlier, i'm an introvert.",
  "i'm a deeply sensitive person, and so that was never my interior life.",
  "that that is not how i process, so i always felt, um, in conflict, um, with the opposing, um, with the with the dichotomy of, uh, what was in my my heart and soul and and what was being projected onto me.",
  "yeah.",
  "i'm i'm actually wondering if you could say more about that.",
  "i was wondering if, like, at the time, you know, it's it sounds like there's just so many people that didn't meet you emotionally where you needed to be met, as a child.",
  "and, um, in a lot of ways, it sounds like there was a lot of culture around, appearances.",
  "we mentioned just performing in a certain way and, maybe even achievement being, like, early on seeded in there.",
  "right? and just not a lot of space for you to, um, have feelings, have emotions, and be able to express them.",
  "and i wonder, like, as a kid, did you have moments where you sorta knew that that was, that didn't feel completely right or that didn't feel met, in some sort of way.",
  "were there any environments or spaces where you were met with maybe some emotions? how did you know this is not how you needed to be held, if at all.",
  "maybe that wasn't even present for you.",
  "like, i always knew that something was something was amiss.",
  "mhmm.",
  "um, however, i just didn't know what to reference it with.",
  "i i didn't know what to benchmark it off of because i didn't see examples of what it would look like to display my all the full range of my emotions of what i was going through.",
  "yeah.",
  "i honestly didn't know, and i still don't fully know.",
  "um, it's a ongoing journey.",
  "it is yeah.",
  "the battle of my life.",
  "i started to realize a little bit more outside of college.",
  "but even then, i think it was hard to make things click because i was choosing things that felt very similar to what i was accustomed to even if i hated it.",
  "can you hear me about that? like, what oh.",
  "what were things you were choosing from that? sure.",
  "so i i think i actually wrote something, um, about this.",
  "um, but in my my heart of hearts, i think, as an adult, working is not where it's at.",
  "yeah.",
  "i'm not lazy.",
  "i'm not lazy.",
  "yes.",
  "but working is not where it's at.",
  "i i i find value in the work that i do now.",
  "it aligns with my north star.",
  "i feel like my energy leads to results, and there is value, and i'm making a difference.",
  "mhmm.",
  "and outside of that, i don't feel like humans should have to go through all these hoops and hurdles just to make a living.",
  "hey.",
  "i i remember in a middle school project, i think it was sixth or seventh grade when we talked about what do you wanna do and be when you grow up, which i i think is ridiculous.",
  "um, we should be pouring into children not, like, poking and prodding them about, okay.",
  "think about your future right now.",
  "um, i i just think it's absurd.",
  "like your future profession.",
  "yes.",
  "yeah.",
  "because i i i think at that time, they're questioning themselves.",
  "they're questioning the world.",
  "they're scared.",
  "i think that should be the time where there's, like, utmost security and confidence building.",
  "and as they grow older, they will then find, um, what it is that they want, and then they'll they'll change.",
  "so teaching them yeah.",
  "the the the the beauty of the pivot of exploring of growth, but that's a that's a tangent.",
  "um, i so in my assignment, i said that i just want to be able to have a life where i can sleep and eat and read.",
  "and then the teacher was like, Ciera you you can have higher ambitions.",
  "you're so smart.",
  "and i'm like, that's great, but i don't want to apply all of my energy into a way of life that i don't even like.",
  "yeah.",
  "but and that was in fourth grade? that was in that was, like, the fourth grade assignment? middle school, six to seven.",
  "yeah.",
  "but you i'm hearing even in middle school, you were like, i just i wanna live.",
  "like, i just wanna live and not have to hold up certain expectations or, um, yeah, or lean into as you mentioned, like, lean into just my productivity being the, like, achievement and the work that i do being the only thing that's important about me or yeah.",
  "i mean, my profession.",
  "yeah.",
  "i just hated it.",
  "but, again, it was it was a culmination of things that kept me prodding on.",
  "so teachers being insistent of, like, you're so smart.",
  "go to college.",
  "you can do this.",
  "and, also, my family seeing that in me too and wanting me to go, and i'm grateful i went.",
  "i love learning.",
  "um, if i'm if i could go back in time, i would still go to university, and i'm currently in grad school right now, so i like it.",
  "um, i just would have changed the path that i took.",
  "so i i think i would have taken a break after my mother passed, um, instead of going right to college because she died a week before my high school graduation.",
  "oh, wow.",
  "i think i wouldn't have dove into achievement after achievement after achievement.",
  "i wouldn't have, like, taken off taken on all these majors in college.",
  "um, i wouldn't have after i graduated, i wouldn't have participated in all the fellowships i did because to be oh, and people might people who i've been associated with may listen to this, but, uh, here i am now, and i'm saying, most of y'all, i didn't even like.",
  "i didn't even like i didn't like the way that y'all rolled.",
  "i didn't like the way that i rolled with with y'all.",
  "mhmm.",
  "um, and there were just some tendencies around how i showed up and, um, also, what i wanted and needed that i didn't get that just felt ick.",
  "yeah.",
  "um, that just felt heavy and gross, and i wasn't moving toward who i was.",
  "i was moving further and further away.",
  "i was pressing the gas in the opposite direction of, like, where i wanted to be.",
  "yeah.",
  "yeah.",
  "there was no doubt in my mind that i was i was broken and trying to hold myself together.",
  "and but in denial about it or maybe not in denial, but just trying to really hold together.",
  "because i felt like if i cracked open, who was gonna help me? who was gonna pick me up? and because i didn't get those safe spaces and reassurance, like, the social emotional part yes.",
  "it was very challenging to identify who those people were going to be.",
  "mhmm.",
  "and so i just kept going.",
  "yeah.",
  "after my mom passed, oh, i i remember my dad came in my my bedroom.",
  "he let me know what had happened.",
  "i just sat there.",
  "i also opened my window, because i just have this thing of just letting energy out or letting a a soul out.",
  "i don't know.",
  "i just think when moments like that happen, you can't just let it linger in the air.",
  "and i've even had some family members pass recently.",
  "so, um, my grandfather on my mom's side passed in janu no.",
  "december.",
  "um, and then my thank you.",
  "and my grandmother on my dad's side passed in january, literally, like, a a week apart.",
  "wow.",
  "um, and so in those moments too, i, like, went i opened a a window or a door in their their living spaces just to let air out.",
  "and so i remember when that happened and i i opened my window on my room i just went into went to planning mode of, okay.",
  "who do i have to tell? who do we need to call? what's the casket gonna look like? mhmm.",
  "what is she gonna wear? what what photos is she gonna have? who's gonna write the bio? who's gonna give the speech at the funeral, what are the songs gonna be, um, who's gonna do my hair.",
  "yeah.",
  "um, so, again, it's like that narrative of, like, the run-in the stocking almost is, like, then it's yeah.",
  "you know, it's like, alright.",
  "what's next? like, yeah.",
  "yeah.",
  "and, um, not really a focus on me.",
  "i don't recall during that whole time mhmm.",
  "if anyone was like, Ciera are you okay? or, Ciera you don't need to do this.",
  "um, we got it.",
  "i and i imagine that people were sad.",
  "people were broken up.",
  "but i think i was like a matriarch in training or, like it was like an expectation on you.",
  "an ex yeah.",
  "an expectation.",
  "and so i was yeah.",
  "yeah.",
  "the weight of it and kept moving yeah.",
  "yeah.",
  "carrying the weight of it.",
  "and once everything was done, i exhaled, and mhmm.",
  "i the summer felt like a blur.",
  "mhmm.",
  "um, but when august so i don't remember anything, and maybe that's just repression.",
  "um, but still don't recall what i did that summer.",
  "um, all i remember is that, boom, i was in pittsburgh.",
  "i had all these boxes, and then i was just, uh, alone in my dorm at one point.",
  "and i was like, okay.",
  "i feel nervous.",
  "and then i was like, okay.",
  "i need to map out my classes and when i'm gonna study and when i'm gonna do this and what activities can i do? and let's or i and i can't go to a party.",
  "i can't date because i don't wanna get caught up in that, and i'm gonna, like, lean in the church really hard because i need to stay steady.",
  "this discipline.",
  "i'm here, like, task oriented and discipline as opposed to, like, um, yeah.",
  "if you were to date, then you would open up your emotions and a potential, like, whatever in a relationship.",
  "um, and that'd be confusing and bring up things.",
  "yeah.",
  "yeah.",
  "yeah.",
  "wow.",
  "and so i'm wondering, like, when did, when did things start to change for you? mean, you shared a little bit about, like, how your identity is, um, influenced how you process grief a little bit.",
  "they influenced it in a way where you weren't really processing your grief a lot as much because it was because what was more important were the logistics of what needed to happen or, um, being able to, like, complete college, um, and map out your classes or do what you needed to do.",
  "and so, what was it about we mentioned the pandemic earlier, but was it the pandemic or was there an earlier time that really gave you space to just, like, sit and really be able to touch into your emotion around it? i would say that for me, i am definitely a slow burner, so things started to change slowly.",
  "and i would say in my first year of college, in the first semester, i had a really bad panic attack.",
  "mhmm.",
  "and i was like, i know where this is coming from.",
  "i'm gonna set up an appointment with therapy the the the therapy center right away.",
  "and i'm like, i don't even know if this is gonna work, but i'm just gonna commit to my appointments every single week.",
  "and i the discipline, but the awareness too.",
  "master discipline.",
  "yeah.",
  "from, like, the first semester of my first year all the way until i graduated.",
  "and then i was like, woah.",
  "i'm no longer paying tuition anymore.",
  "where do i go? and then did my own research, and i was like, okay.",
  "i'm gonna go to duquesne, which has a really great therapy program.",
  "mhmm.",
  "um, so if anyone's listening in pittsburgh, um, and they have, like, a sliding scale.",
  "and so after undergrad, i just started i just kept going, and, uh, things just started, like, chipping away.",
  "uh-huh.",
  "and it wasn't until i had my first therapist of color where i felt safe to talk about sorry.",
  "that's my dog, maya.",
  "you hear her? hi, maya.",
  "maya.",
  "maya is also saying, thank god for therapy.",
  "yes.",
  "yes.",
  "mommy, come here.",
  "sorry.",
  "yeah.",
  "no.",
  "nobody need to be sorry.",
  "you're a dog mom.",
  "that's also part of your identities too.",
  "yeah.",
  "oh my gosh.",
  "hold on.",
  "alright.",
  "so we're back on, and maya will be joining us.",
  "that's great.",
  "hi, maya.",
  "because she can't be left to her own devices.",
  "so someone aw.",
  "is greeting my neighbor across the hall, and she's like, who's that? i need to be involved in everything.",
  "but now she's just on my lap.",
  "especially glad you can join us.",
  "yes.",
  "so where oh, yes.",
  "um, i i finally had a therapist of color who helped me connect the dots between, like, growing up as a a black woman and but living in this very white space and not having the space to really share how i felt or and also thinking about all the other spaces i've been in that weren't culturally responsive and, um, how i had to hold in what i felt.",
  "and she imagined that i i felt angry and sad and, uh, uh, alone, and she just, like, hit the nail on that head.",
  "yeah.",
  "can you, like, share a little bit more about that? i think that's so important what you just mentioned about being a black woman in, predominantly white spaces and how that impacted maybe not being able to grieve as much or not being able to start a healing process.",
  "can you just go a little bit into, like, how that impact you? sure.",
  "um, so after my mom passed, i you know, i honestly think that my experience would have been different if i went to atlanta or dc or or new york or or chicago or for college.",
  "yeah.",
  "i chose one of, like, one of the whitest cities in america.",
  "yes.",
  "okay.",
  "and i not to dis discount, um, the experiences of bipoc folk in those areas because i witnessed that people are building community and and living and and leading.",
  "um, and at the same time, um, i do think that in predominantly white spaces, there's so many norms, um, that are implicitly and or explicitly enforced around how you're supposed to show up if you're not within the the dominant narrative or the majority.",
  "and so for me, i don't think that there was space to to be my full human self and say, well, i'm i'm sad.",
  "or yeah.",
  "the system failed me, um, because if there wasn't medical racism that that that lets my mom receiving subpar care and then experiencing, like, the bulk of her life in the health care system, and then my dad being, uh, a working class, my brother having cerebral palsy, um, but not being fully supported by by the state, and my dad having to spend the bulk of his time taking care of my mom and then also fighting to make sure that my brother had the care that he needed, which meant that for me, you you know, everyone did the best they could and and got me to the other side yeah.",
  "yeah.",
  "of to to adulthood, and i turned out so great, and i love them.",
  "but there are so many things before i even got to pittsburgh that were rooted in white supremacy and systemic oppression that affected the trajectory of my family and also how i didn't have a grieving process.",
  "yeah.",
  "um, when i, um, went to ethiopia, um, for my fulbright, also, when i lived in the gambia, um, for a study abroad, when people passed away it's a completely different process and experience.",
  "there's time and space, and people are openly emoting what they feel.",
  "um, even in their their the written languages of Amharic um, in ethiopia and and wolof in the gambia, um, there there are words for emotions that would be really hard to describe in english in the us.",
  "i also like seeing that, like, for for the first maybe for the first time, seeing people openly grieve in those spaces.",
  "um, it felt a little overwhelming because there was just a a lot.",
  "um, and then i also felt conflicted because there were many spaces in which i was told i couldn't be that.",
  "i couldn't be a lot.",
  "or i was told that if i did, that would be extra.",
  "but being a space where my ancestry is connected to, i don't know all the the pieces, um, but my ancestry is connected to.",
  "so likely, i have people in my lineage that would have grieved in similar ways.",
  "and then living, um, in the us, um, where things feel very sanitized very disconnected.",
  "so i'm hearing you say that, like, there's not space for you to be able to emote in those ways or even learn about that at all in the us, we talk about funerals.",
  "we talk about maybe celebrations of life and memorial services more in, like, black community.",
  "right? but aside from that, there aren't necessarily specific ways that, are necessarily taught very openly in communities that we hear about, like, in school or unless you are part of those communities.",
  "is that right? yeah.",
  "but i i would also say that and i i don't have the words for it.",
  "i do think in in some black traditions here, there is, um, there are some traditions that i can see through lines in, like, um, the celebration of life and there being lots of song and even and dance and, like, a procession that is is very similar to what i noticed in west africa when i lived there.",
  "but then there are parts where it feels, wow.",
  "this is very western, um, or this is very american where it seems blunted.",
  "like, there's, like, a a time frame in which you you must get this done, like, in terms of the the cell the ceremony.",
  "mhmm.",
  "like, if we start at one, we're gonna end at three.",
  "or all of this costs thousands of dollars for you to do.",
  "or as opposed to to the community pulling funds together to support a family who is grieving.",
  "good point.",
  "yeah.",
  "yeah.",
  "or, okay, maybe the first week, people will make meals for you.",
  "but after that, you're on your own, whereas i've noticed that, oh, people will check on others for life, especially if the person who died was like a a head figure in the family, um, or if someone lost a child, um, there was just something it was just different.",
  "and, of course, it's it's culture to culture, and i'm sure that there are european cultures as well, um, in the west that that do have more layered and more emotive processes.",
  "and i'm speaking from just my observation yeah.",
  "in the united states that there are and i don't again, because i i'm not an expert in this, but i feel like someone should write a paper on, um, like, western, like, american funeral practices and grief practices.",
  "like, there's something in the air that affects the way in which we we talk about it, um, or the way that we we don't talk about it.",
  "and not just this, i think, we because i just felt like this is so connected to uh, america's attachment or our our tolerance of violence, but low tolerance of conflict.",
  "and i do think grief is conflict, um, because you're you're you're wreck you're reckoning with past and present and future.",
  "mhmm.",
  "um, you are reckoning with yourself and and also the person who passed.",
  "and from from doing deib work, i i can i can tell you that people have an aversion to conflict? mhmm.",
  "ready to get in some violence, ready to watch violence, ready to to like, oh, no.",
  "like holding the tension.",
  "and yeah.",
  "i'm wondering the and maybe we started to get into it a little bit, but how did the pandemic specifically give you space to grieve? or as you said, grief is conflict.",
  "how did the pandemic give you space to maybe wrestle with that conflict internally? i think it it caused things to slow down or just stop.",
  "i think for me, i had a lot of a lot of things in the way.",
  "um, work, working a job i didn't really like, entering a job i didn't really like.",
  "honestly, i moved for a job that i thought was something else, but it turned out to be completely different.",
  "and i'm like, oh, well, i'm here already in the area.",
  "and then i i also was doing a bunch of things, reading a bunch of things, listening to a bunch of things, and then the world just stopped.",
  "and all the things i was tethered to, whether that was people or or things, didn't they were far away, or they just didn't matter anymore.",
  "and i was just in my my little apartment with my thoughts and, um, also thinking about, well, am i at where i wanna be, or am i behind? and i just came to the conclusion that i'm lost because i was just so focused on carrying on, that i really wasn't being me.",
  "and and then it it made me think and this is also the the ten year anniversary of my mom's passing.",
  "and so it made me think of, oh, that's that's huge.",
  "that's huge.",
  "that's big.",
  "that is huge.",
  "it's very big.",
  "and that was that was the pandemic was the tenth.",
  "yeah.",
  "yeah.",
  "so twenty twenty.",
  "yeah.",
  "yeah.",
  "and oof.",
  "just sitting with that and then not being able to really do anything.",
  "mhmm.",
  "um, not being able to visit her grave on on mother's day and at the time, i i hadn't gone anyway.",
  "um, i just wasn't ready.",
  "yeah.",
  "yeah.",
  "but then it didn't mean you weren't thinking about it either.",
  "i wasn't thinking about it.",
  "yeah.",
  "that doesn't mean i wasn't thinking about it.",
  "i just wasn't ready.",
  "sure.",
  "um, but the pandemic made me think about, well, what if i catch covid and it's it's a wrap because this was before the vaccines? and what if i never get that opportunity? wow.",
  "um, but i was also thinking about what what are some things that i really wanted to do but just couldn't do, um, because my mom is gone.",
  "oh.",
  "so i remember once thinking about, wow.",
  "i wish i could just go to the woods, but i don't drive.",
  "i don't have a license.",
  "i just got sad about well, typically, people's parents teach them how to drive.",
  "and so feeling a lot of grief about certain milestones or just things that i i couldn't do, um, because my relationship with my family figures was so different or, wow, like, i can't talk to my mom about certain things or, um, it it just all kinda hit because, well, i couldn't hide it.",
  "and, also, it it was okay to not hide it because who else was seeing? i didn't really have to perform at work.",
  "i just, uh, anytime i had a meeting on zoom, i would, like, pop on and then pop off.",
  "and so there really wasn't any expectation to be a way or do things in a way, um, for other people's comfort.",
  "i didn't need to be palatable.",
  "oh, that's what changed.",
  "i'm hearing that was, like, the change.",
  "yeah.",
  "yeah.",
  "and so i just let it flow and just, um, did some backtracking on okay.",
  "there are some things that i'm doing that i i don't have to do.",
  "i can undo these things.",
  "um, i can get out of these things.",
  "and, um, um, so there's some when i moved to seattle, there were some some people that, i don't know, i just, like, stopped talking to.",
  "mhmm.",
  "um, there are some things that i just stopped engaging in.",
  "there were spaces that i just didn't wanna be in anymore because i joined them because i was in duress.",
  "i was trying to keep my my head above and also they weren't soft spaces.",
  "they weren't like loving spaces.",
  "and so i think the pandemic and thinking about my mom just made me do a double take and and think twice about, okay.",
  "how do you really wanna show up? and who do you want around you? who do you want? yeah.",
  "you're in, like, who do you want around you? how do you wanna show up? and the questions that you asked yourself were just so important around, who do you wanna be? there were so many pieces that kinda came together during the pandemic, it sounds like, that gave you the space to reflect, but also, think about like, i want things to shift and change.",
  "like, i don't wanna talk to i don't wanna talk to the people that i was talking to.",
  "i don't wanna do the things that i am doing.",
  "i wanna do something different.",
  "yeah.",
  "and i it made me also be more even more intentional in therapy and, um, more intentional about the skills i really want to learn.",
  "am i doing things for me, or am i doing things because other people said that i need to be doing these things? yeah.",
  "and i think why i was so focused on that is because my mom didn't really get to fully live her dreams.",
  "um, right before she passed, she had enrolled in culinary school because she likes to to cook.",
  "and, um, apparently, according to the story, she was a really good cook.",
  "and but then when she got incredibly sick, and this was after her last stroke that i witnessed, um, she was unable her body was unable to move in the ways, um, that they used to, and so she could not cook in the way that she used to.",
  "yeah.",
  "and she was in her last trimester of culinary school wow.",
  "but passed, um, passed away.",
  "she didn't she didn't get to cross the stage.",
  "she didn't get to pursue what she loved.",
  "and so another thing that i thought about was not what what am i supposed to make of this? yeah.",
  "and so it it led me to think about, well, i wanna make sure that i i do what i wanna do and also break some generational stuff, that i felt, like, was not only plaguing my mom, but but plaguing other women in my life.",
  "like, i i i don't wanna be i don't wanna if i ever have a grandchild, i don't wanna tell them that they can't cry.",
  "and all this is coming from a place of survival.",
  "and very much rooted to me and, again, i'm not an expert, but i feel like it's rooted in the dna of of people black people living in the us who are descendants of or of enslaved people of holding grief because you could get in trouble recognizing that separation and grief is just a part of the narrative for us.",
  "so you keep pushing.",
  "uh, i do think that there's a connection there, but i i felt like twenty twenty was, like, for me, a portal into a new way of being.",
  "i don't have to be what was.",
  "and expectations that were, on you either.",
  "yeah.",
  "yeah.",
  "and so i knew that i wanted to go to grad school, but was just kind of, like, scared of is this information overload? am i am i doing this because i really want to or because other people are telling me to? so i used discernment and then did use that time to research degree programs.",
  "yeah.",
  "um, i also began to learn how to drive.",
  "i'm still learning how to drive.",
  "k.",
  "um, because it's a slower process when you don't have, like, community members, like, round the clock giving you that space.",
  "so i'll get my license when i get my license.",
  "i also, um, started taking better care of my health and especially with ms, um, that i have to be very mindful and be an advocate for myself.",
  "and, also, i learned that releasing trauma from the body is also helpful in in alleviating symptoms for my ms.",
  "and so grieving was another part of the process that i needed to do and i'm still doing.",
  "yeah.",
  "yeah.",
  "i also, i just tried to lean into things i was really interested in and try to let my heart guide me because i think that one of the sad parts about one of the many unfortunate parts about my mom's passing is that she wasn't even fifty.",
  "like, she was in her late forties, and i think that that's still, like that's so young.",
  "yeah.",
  "it is young.",
  "you're still living your life, and your people pivot around that age.",
  "mhmm.",
  "people have other awakenings at that age.",
  "mhmm.",
  "and my mom never got to have that.",
  "and so it it just made me think, well, i perhaps if if she were still alive or perhaps if i'm in tune with her presence, like her her spiritual presence, i think me pressing pressing on in a way that's healthy.",
  "yeah.",
  "not in a way that's been prescribed to me, but pressing on in the ways that i want to, like yes.",
  "distinguish that.",
  "yeah.",
  "getting a license and traveling and trying new things, being able to expand in the ways that she could not mhmm.",
  "is one way of keeping her alive mhmm.",
  "but also honoring her, but also planting seeds so that we there aren't other women in my family who die before they get to come into who they are.",
  "important note.",
  "yeah.",
  "yeah.",
  "yeah.",
  "and i i just i hear you as you share that that it goes back to something that you said earlier of, like, allowing yourself to pivot or pivoting being import like, an important thing, that's just different than pressing on.",
  "it's actually just it's unlearning the having to press on and allowing yourself to be able to change if you want to.",
  "and, um, to be able to do that at an age, because we don't know how much time we have.",
  "but you're absolutely right.",
  "that really that resonates even, like, as you were sharing that.",
  "i was like, oh, that resonates with my own story, right, of having having, um, moms and and relatives in our lives who have passed away when they were young and, um, you know, wondering what else they would have done or what they could have witnessed, seeing us do.",
  "or be as people.",
  "yeah.",
  "i'm wondering, you know, you've dropped so many so much good wisdom i just wanted to give you so much space to share.",
  "i feel like you've shared about your identities, how they've, you know, impacted grief and healing and maybe even some rituals and traditions that you, learned about.",
  "and, some wisdom as we're sort of, like, wrapping up and thinking about things, i'm wondering, kind of two things.",
  "so maybe i'll start with this first question of, like, you've shared how grief and healing have sort of shaped your identity, i'm wondering what's been the most important thing you've learned in being with and processing your grief? um, and then maybe also, like, what's been one of the most important things you've learned about healing, um, as part of, yes, you have grief and you also have healing too? one of the most important things i've learned from being with and processing my grief, um, um, is that it's important to connect with your your cultural or ancestral practices.",
  "can you say more? like, in relation to yourself? yeah.",
  "going back to the revelations i had living in africa for a little bit, um, and seeing how those practices of grieving were drastically different from the ones i've been conditioned to accept.",
  "mhmm.",
  "um, i do think that there is wisdom, um, in in our roots, um, around how we are how we hold, um, our dear ones who who have have passed away.",
  "mhmm.",
  "um, and for me, i think when i was able to fully immerse myself in a practice that felt resonant with with who i am.",
  "mhmm.",
  "it felt more authentic and and and just real in a way that the process i experienced at eighteen was not.",
  "and and even and even if people don't know, um, because it's very real for many of us.",
  "mhmm.",
  "um, we might not know what that looks like.",
  "but honoring how you wanna grieve is very essential.",
  "so if you are not a whaler and you just wanna walk in the woods, that's fine.",
  "mhmm.",
  "if you are if you wanna grieve through writing, that's fine.",
  "there's so many ways um, that i have been able to to process that i i didn't know about until later, um, but i just clung to because that that just it just clicked.",
  "mhmm.",
  "i would also say that in terms of the cultural practices, there are some practices that i took for granted, like saving, um, funeral programs or, um, saving articles of clothing, um, that thankfully my dad was thinking about and did for me.",
  "and so i now have those those relics and those pieces of my mom that i can hold on to.",
  "i also think engaging in the practices of your loved one, um, is also a a healing practice too.",
  "so my mom used to collect spoons.",
  "oh.",
  "i collect spoons because i knew that there were places that she wanted to get to that she didn't get to visit that i was able to carry on and and do for and with her.",
  "mhmm.",
  "and i feel like that that creates a sense of wholeness for me.",
  "yeah.",
  "um, what amazing connection too to, like, it's a that that continues, that tradition of that she and hobby that she had.",
  "mhmm.",
  "and i would also say that grieving is a privilege.",
  "oh, can you say more? okay.",
  "yes.",
  "for sure.",
  "i it is not surprising to me that i not only had the space during covid, but i also had the space because i was making six figures, and i was working a job that allowed me to be remote.",
  "and mhmm.",
  "there are many folks that during covid didn't have that opportunity or that privilege to earn that much, especially in a city like seattle.",
  "that's right.",
  "and there are people who, even before and after the pandemic, didn't have that and likely won't have the flexibility, um, or the financial resources to be able to grieve.",
  "because i think that my grieving process is so different from my father's, um, solely because, um, he was he's working class.",
  "mhmm.",
  "um, and he is a caregiver to my brother, so he never got the break or the space that i did.",
  "and i also think about other people in my life who they had to carry on because what was the space? they don't they can't take a a paid vacation.",
  "yeah.",
  "yeah.",
  "and so i think there's something and and it's larger than us.",
  "it's a systemic thing.",
  "and may and that's another reason why i feel like the that america is just we're we're so i don't think we we have met the mark of of how to grieve because we're not creating a structure for it.",
  "and a part of me wishes that if i were if i had if i had the social and financial capital, i think it would be very powerful to have a grief sabbatical oh.",
  "um, like a fund for people who they need bereavement leave, but they can't afford to do it.",
  "so they're just crumbling and falling apart or holding it in, and that manifests in their body.",
  "and i'll just stop there because sierra, i feel like you have a good idea that maybe we, in the future, on this back ass, maybe we need to build on in some sort of way.",
  "right? to your point in the beginning of, like, if there isn't something, sometimes we have to create it.",
  "and so i i agree having that having the space to be able to do that, but also, like, the things that you're naming time and money, um, and space to be able to have that ability to be able to grieve well is a privilege.",
  "and being able to lower barriers to be able to do that is something that, um, could be mutually funded.",
  "yeah.",
  "yeah.",
  "in a community collective way.",
  "yeah.",
  "yeah.",
  "mhmm.",
  "um, i just have a final question for you.",
  "yes.",
  "i'm wondering, you know, you've you've shared so many gems, so i feel like you maybe answered this question.",
  "but i'm just wondering if there are myths that you've heard about grief or healing.",
  "i'm wondering, what do you wish people knew about this topic? or you can also take this question instead.",
  "what do you wish you knew that you know now, but you didn't know then so i'll actually try to address both.",
  "that's what i thought.",
  "it feels like it's in the realm of both.",
  "so myths that i've heard and what i wish i knew.",
  "grief and healing doesn't have a time stamp.",
  "i think that it is ongoing, and it will ebb and flow.",
  "you will move forward.",
  "you will also move backwards.",
  "um, there it's not a test that you take, and you you you do it well.",
  "i think that there's an assumption.",
  "and that's why our bereavement reeve in the unite bereavement leave in the united states is so abysmal because people think, here's your three days three days.",
  "if you get that.",
  "if you get that.",
  "yes.",
  "you know, send us the, um, the program from your funeral so we can, like, put it in our system and, you know, so we can you can prove that something actually happened to you.",
  "and then, you know, you're good.",
  "come back to work.",
  "here's some casseroles.",
  "you know? bye.",
  "good luck.",
  "um, no.",
  "most of the the heavy stuff in my experience happened after everyone left.",
  "yeah.",
  "um, after your your pto was gone, and that and that is a heavy a heavy weight to hold, especially alone.",
  "mhmm.",
  "and i i one thing that i i wish that people knew is that, um, there is power in checking in.",
  "mhmm.",
  "um, there's power in community.",
  "um, there's power in that community being attuned to what people need.",
  "um, i i think there's no way that people can can get through on their own on this.",
  "and, honestly, i i mentioned earlier in our talk that grieving my mom is is one of the the battles of my life, and i i think it is.",
  "i think for most people, um, you know, they're not gonna be, like, in the thick of it all the time, every time.",
  "but it's it's just something that is not going to go away because, like, someone who is a part of you, um, and in my case, someone who made me yes.",
  "yes.",
  "is gone, and that leaves a gap.",
  "yes.",
  "um, it's like, you know, you can try like, in a in a puzzle where you know, like, okay.",
  "we're missing this color, this piece.",
  "you can try to stick, like, a little puzzle in there that sort of that sort of fits.",
  "um, but it you know that it's not the same.",
  "mhmm.",
  "um, and so that's what you like, if you squint, like, okay.",
  "it looks okay.",
  "but it's always gonna be change.",
  "it's always gonna feel different.",
  "yes.",
  "and i think, um, people i think it's important for people to remember that and be mindful of that.",
  "and, also, it's sometimes you have to think about your discomfort when you're witnessing someone in distress or sadness because i also think that folks in the united states, um, don't there is an aversion to pain.",
  "feeling it, seeing it.",
  "and when people grieve, they're in pain.",
  "and so yeah.",
  "i think and i know for me that knowing that people were averse to it and didn't wanna talk about it, i'm like, okay.",
  "so i'm not gonna talk about it.",
  "uh, i'm just gonna hold it in.",
  "i'm gonna, like, project confidence and strength.",
  "when in reality, i was falling apart.",
  "mhmm.",
  "and i think as i noticed people grieving, things that i'm doing differently in terms of how i support people that i notice are grieving is, like, if i observe, oh, they're they're not eating.",
  "yeah.",
  "can i send you a doordash? or, oh, they they need to tidy up some stuff around here.",
  "mhmm.",
  "can i be your folding buddy? or do you want me to be in the room as you fold? because not everyone likes to have their things touched by by people who are not them.",
  "um, or wow, you i know you're sad.",
  "i see the pain in your face.",
  "we don't have to talk about it, but i'm not gonna push you to be in this meeting or do this thing.",
  "you know, you are where you're at.",
  "then that's it.",
  "and so just making sure that we are also checking ourselves to create spaces for people so that they can have their process too.",
  "yes.",
  "these are so, uh, these are so good.",
  "i think sometimes, the thing i've heard from people is like, i don't know what to say.",
  "i don't know what to do.",
  "well, sarah just gave you some things that you can say or do, um, because, yeah, we do we are in a culture where there's a lot of discomfort around grief.",
  "um, there's a lot of discomfort around pain.",
  "people are pain averse.",
  "people, you know, um, don't want to necessarily always deal with all parts of you.",
  "and it's important for us to meet each other where we're at.",
  "and so i i'm just so grateful.",
  "thank you, sierra, for just sharing so much of yourself and also just sharing, you know, real, you know, there's so many practical gems you shared and so many pieces of wisdom.",
  "and, as we wrap up, i was just wondering if our listeners would like to connect with you, if that's okay with you.",
  "oh, for sure.",
  "um, then i love for you to share, how can people stay connected with you? how can people learn more from you or, um, maybe engage in some of the services that you're involved with? yeah.",
  "and i'll share in the show notes.",
  "sure.",
  "so i i just started my dei consulting, dei consulting llc, uh, the do better project, and i i started it because i was seeing some crappy dei, um, and i think it that that was a a result of twenty twenty.",
  "it just, like, burst the the market wide open.",
  "um, and but i noticed that it was either you know, we don't really need to interrogate ourselves and how we show up in spaces.",
  "diversity is important.",
  "um, celebrate the heritage months and you'll be fine, which that's not it.",
  "mm-mm.",
  "or, hey.",
  "you're not ready, but you have to get ready.",
  "and so you can't swim, but you're gonna be diving off of this this board into the deep end wow.",
  "at the end of this workshop, and that doesn't work either.",
  "um, i think it's more about understanding who you are as a person and then letting that define the gap between where you are and where you wanna be and then giving people the specialized skills based on where they're at and who they are to get to the other side.",
  "love it.",
  "and so my my work is more relational, um, and it's a it's multidisciplinary.",
  "so, um, there are so many aspects of dei instead of just reading a book from a book club.",
  "yes.",
  "there is you've gotta learn how to speak.",
  "you'll you have to learn how to move in community.",
  "you have to learn how to, like, be comfortable with your emotions.",
  "and so this is some of the work that i do.",
  "and if that resonates, my practice resonates, you are more than welcome to email me at it's a very long email.",
  "the, t h e, do, d o, better, b e t t e r, project, p r o g e c t, and then l l c at g mail dot com.",
  "as i evolve, i imagine i'll get a better email.",
  "that's great.",
  "everyone needs to do better, so you can remember that, the do better project llc.",
  "yes.",
  "that's great.",
  "and any other types of connections, you can find me on linkedin.",
  "i'm not really a social media person, but i do check my linkedin, um, at least once a week.",
  "love it.",
  "linkedin.",
  "and you also heard sierra list her email.",
  "like i said, i'll put it in the show notes.",
  "sierra, thank you so much for your time today.",
  "appreciate you.",
  "and, also, thank you so much for sharing so much of yourself.",
  "we appreciate you.",
  "appreciate you as well.",
  "happy to help.",
  "yeah.",
  "thanks."
]